[build]
  command = "bun run build"
  publish = "dist"

# 🔹 Configure SPA (Single Page Application) Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# 🔹 Cache STATIC assets (CSS, JS, Images, Fonts) to improve performance
[[headers]]
  for = "/*.{js,css,woff2,woff,ttf,eot,svg,ico,json,webmanifest}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Cache IMAGES aggressively (avoid reloading unchanged images)
[[headers]]
  for = "/*.{png,jpg,jpeg,gif,webp,avif}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Ensure the Service Worker (`sw.js`) updates immediately
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# 🔹 Ensure `manifest.webmanifest` updates properly (avoid PWA caching issues)
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"