[build]
  command = "bun run build"
  publish = "dist"

# Redirect all routes to index.html for SPA support
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure service worker updates correctly
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Workbox files should be updated when new versions are available
[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Index.html should allow revalidation for offline-first support
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache static assets for a long time (1 year)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images and icons aggressively (1 year)
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Allow IndexedDB and localStorage usage (CORS and storage policies)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, must-revalidate"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    X-Content-Type-Options = "nosniff"

# Cache manifest for PWA (ensure updates are fetched)
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache fonts properly (1 year)
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Ensure JSON files used in IndexedDB/localStorage can be cached
[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
