[build]
  command = "bun run build"
  publish = "dist"

# 🔹 Redirect All Routes to index.html (Fix SPA Routing in Netlify)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# 🔹 Cache STATIC assets (JS, CSS, Fonts, JSON, Icons, etc.)
[[headers]]
  for = "/assets/**"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Cache IMAGES aggressively (Reduces reloads)
[[headers]]
  for = "/images/**"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 🔹 Ensure Service Worker updates immediately (Crucial for UI Updates)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# 🔹 Ensure Service Worker updates immediately (Crucial for UI Updates)
[[headers]]
  for = "/src/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# 🔹 Prevent Caching of `index.html` (Ensures UI Changes Appear Immediately)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"