[build]
  command = "bun run build"
  publish = "dist"

# Redirect all routes to index.html for SPA support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Ensure service worker updates correctly in Netlify
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"